import {
    BLOB,
    DATA,
    NONCE,
    NONE,
    SELF,
    STRICT_DYNAMIC,
    TLD,
    EVAL as UNSAFE_EVAL,
    INLINE as UNSAFE_INLINE,
    WASM_UNSAFE_EVAL,
} from 'express-csp-header';
import type {CSPDirectiveName} from 'express-csp-header';

export const CSPValues = {
    NONE,
    SELF,
    NONCE,
    UNSAFE_EVAL,
    WASM_UNSAFE_EVAL,
    UNSAFE_INLINE,
    TLD,
    STRICT_DYNAMIC,
    DATA,
    BLOB,
} as const;

export const CSPDirectives = {
    BASE_URI: 'base-uri',
    MIXED_CONTENT: 'block-all-mixed-content',
    CHILD: 'child-src',
    CONNECT: 'connect-src',
    DEFAULT: 'default-src',
    FONT: 'font-src',
    FORM: 'form-action',
    FRAME_ANCESTORS: 'frame-ancestors',
    FRAME: 'frame-src',
    IMG: 'img-src',
    MANIFEST: 'manifest-src',
    MEDIA: 'media-src',
    OBJECT: 'object-src',
    PLUGIN_TYPES: 'plugin-types',
    PREFETCH: 'prefetch-src',
    REFERRER: 'referrer',
    REPORT: 'report-uri',
    REPORT_TO: 'report-to',
    SANDBOX: 'sandbox',
    SCRIPT: 'script-src',
    SCRIPT_ATTR: 'script-src-attr',
    SCRIPT_ELEM: 'script-src-elem',
    STYLE: 'style-src',
    STYLE_ATTR: 'style-src-attr',
    STYLE_ELEM: 'style-src-elem',
    INSECURE: 'upgrade-insecure-requests',
    WEBRTC: 'webrtc',
    WORKER: 'worker-src',
} satisfies Record<string, CSPDirectiveName>;
